[package]
name = "priority-queue"
version = "1.2.1"
authors = ["Gianmarco Garrisi <gianmarcogarrisi@tutanota.com>"]
description = "A Priority Queue implemented as a heap with a function to efficiently change the priority of an item."
repository = "https://github.com/garro95/priority-queue"
documentation = "https://docs.rs/priority-queue"
readme = "README.md"
keywords = ["priority", "queue", "heap"]
categories = ["data-structures", "algorithms"]
license = "LGPL-3.0 OR MPL-2.0"
edition = "2018"

build = "build.rs"

[badges]
travis-ci = { repository = "garro95/priority-queue", branch = "master" }

[build-dependencies]
autocfg = "1"

[dependencies]
indexmap = { git = "https://github.com/cosmicexplorer/indexmap", rev = "231e4358ddb850a22d3c2e90e58328f9dbb8a092" }
serde = {version = "1", optional = true}

[dev-dependencies]
serde_test = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = {version= "0.8", features = ["v4", "serde"] }
hashbrown = "0.9"

[features]
benchmarks = []

[workspace]
members = ["test-nostd"]
